### ISSUE TITLE
Лишние знаки "%"

### ISSUE THREAD

**Issue by MAXbrainRUS** [esokolov/ml-course-msu#2]
В файле https://github.com/esokolov/ml-course-msu/blob/master/ML15/lecture-notes/Sem05_metrics.pdf в главе "Индекс Джини" во фразе "В то же время индексы Джини были улучшены с 0.6% до 0.8%" знаки "%" явно лишние. Вообще исходя из формулы выше должно быть  "с 0.64 до 0.81"

**Comment by esokolov** [comment]
Проценты действительно лишние, исправил — большое спасибо, что сообщили! А вот про сами числа не очень понял. Там написана формула Gini = 2 AUC - 1, по которой как раз получаем
2 \* 0.8 - 1 = 0.6
2 \* 0.9 - 1 = 0.8
Можете пояснить, в чем именно проблема?

**Comment by MAXbrainRUS** [comment]
Да, с числами все в порядке, я не на ту формулу посмотрел.
